name: Re-Run Unverified PRs
on:
    workflow_dispatch:

jobs:
  send_pull_requests:
    runs-on: ubuntu-latest
    name: Re-Execute any Autotest PR checks
    steps:
      - name: listPullRequests
        uses: buildsville/list-pull-requests@v1
        id: list
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: '["autotest"]'
      - name: output
        run: |
          echo "${{ steps.list.outputs.pulls }}" > pr.list
          sed -i -E 's/\\n/\n/g' pr.list
          cat pr.list |grep http > pr2.list
          cat pr2.list
          while read pr; do
            echo "$pr"
          done <pr2.list
          #gh pr checks --rerun