name: Re-Run Unverified PRs
on:
    workflow_dispatch:

jobs:
  send_pull_requests:
    runs-on: ubuntu-latest
    name: Re-Execute any Autotest PR checks
    steps:
      - uses: actions/checkout@v3

      - name: Empty Commits
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git branch -r >branches.list
          cat branches.list|grep \/diff\/ |sed 's/^origin\///g' >branches2.list
          cat branches2.list                
  