name: Re-Run Unverified PRs
on:
    workflow_dispatch:

jobs:
  send_pull_requests:
    runs-on: ubuntu-latest
    name: Re-Execute any Autotest PR checks
    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{secrets.GITHUB_TOKEN}}


      - name: Empty Commits
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          ls -al
          pwd
          #cd $GITHUB_WORKSPACE
          sh rerun_checks.sh unverified
