name: Update Shortnames for all PRs
on:
    workflow_dispatch:
#    schedule: 
#      - cron:  '00 5 * * *'

jobs:
  update_shortnames:
    runs-on: ubuntu-latest
    name: Update shortnames for PRs without shortnames
    steps:
      - uses: getsentry/action-github-app-token@v2
        name: Get GH App token
        id: podaac-cicd
        with:
          app_id: ${{ secrets.CICD_APP_ID }}
          private_key: ${{ secrets.CICD_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with: 
          token: ${{ steps.podaac-cicd.outputs.token }}
      - name: retrieve list of open PRs
        run: |
          gh pr list --state open --label autotest --limit 500 >branches.list
          cat branches.list|grep diff\/ |sed 's|^.*diff/|diff/|g' |sed 's|\t.*||g' >branches2.list
          cat branches2.list
